import "./globals.css"
import { Inter } from "next/font/google"
import Navbar from "../components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Booking system",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-3 pt-3 md:px-6 md:pt-6`}>
        {children}
      </body>
    </html>
  )
}
